sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: hugo
    local_dir: public
    repo: DonnotPanic/Epistemophilia
    fqdn: <custom-domain-if-needed>
    target_branch: gh-pages
    email: murundong@163.com
    name: DonnotPanic
