sudo: false
dist: xenial
language: python
python: 3.7
# 使用python下载已发布的hugo安装更快

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -yq install apt-transport-https
install:
  # install latest hugo release version
  - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}' | xargs wget
  - sudo dpkg -i hugo*.deb
  - rm -rf public 2> /dev/null
script: hugo

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: hugo
    local_dir: public
    repo: DonnotPanic/Epistemophilia
    fqdn: <custom-domain-if-needed>
    target_branch: gh-pages
    email: murundong@163.com
    name: DonnotPanic
