baseurl = "https://chronicat.xyz"
title = "Epistemophilia"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "chronicat-xyz"

[params]
    author = "ChroniCat"
    description = "Dig into a cat's thought"
    keywords = "blog,developer,personal"
    info = "Curious Mediocrity"
    avatarurl = "images/logo.png"
    footercontent = "But the sea and the shore will remain forever."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"
    
    math = true
    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/DonnotPanic/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.cn]
        languagename = "Chinese"
        title = "Epistemophilia"

        [languages.cn.params]
            author = "ChroniCat"
            info = "求知的庸才"
            description = "子非猫，安知猫之乐。"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = "海洋和沙岸却将永远存在。"

        [languages.cn.menu]

            [[languages.cn.menu.main]]
            name = "关于"
            weight = 1
            url = "about/"

            [[languages.cn.menu.main]]
            name = "博客"
            weight = 2
            url = "posts/"

            [[languages.cn.menu.main]]
            name = "项目"
            weight = 3
            url = "projects/"

            [[languages.cn.menu.main]]
            name = "联系方式"
            weight = 5
            url = "contact/"
