baseurl: "https://donnotpanic.github.io/Epistemophilia/"
title: "Epistemophilia"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
enableInlineShortcodes: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

languages:
  en:
      languageName: "English"
      weight: 1
      taxonomies:
        category: categories
        tag: tags
        series: series
      profileMode:
            enabled: true
            title: ChroniCat
            imageUrl: "https://donnotpanic.github.io/Epistemophilia/images/logo.png"
            imageTitle: ProfileMode image
            subtitle: "Curious Mediocrity"
            buttons:
                - name: Blog
                  url: posts
                - name: Tags
                  url: tags
      menu:
        main:
            - name: Archive
              url: archives/
              weight: 5
            - name: Search
              url: search/
              weight: 10
            - name: Friend
              url: friends/
              weight: 20

  zh:
      languageName: "中文"
      weight: 2
      taxonomies:
        category: categories
        tag: tags
        series: series
      profileMode:
            enabled: true
            title: ChroniCat
            imageUrl: "https://donnotpanic.github.io/Epistemophilia/images/logo.png"
            imageTitle: ProfileMode image
            subtitle: "求知的庸才"
            buttons:
                - name: 博客
                  url: posts
                - name: 标签
                  url: tags
      menu:
        main:
            - name: Archive
              url: archives
              weight: 5
            - name: Search
              url: search/
              weight: 10
            - name: Friend
              url: friends
              weight: 20
outputs:
  home:
      - HTML
      - RSS
      - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ChroniCat's Blog
  description: "But the sea and shore will remain forever"
  keywords: [Blog, Portfolio, PaperMod]
  author: ChroniCat
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true

  socialIcons:
    - name: github
      url: "https://github.com/DonnotPanic"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/DonnotPanic/Epistemophilia/tree/hugo/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai